/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedOptimizeRouteImport } from './routes/_authenticated/optimize'
import { Route as AuthenticatedFuelsRouteImport } from './routes/_authenticated/fuels'
import { Route as AuthenticatedEnginesRouteImport } from './routes/_authenticated/engines'
import { Route as AuthenticatedDatasetsRouteImport } from './routes/_authenticated/datasets'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCompareRouteImport } from './routes/_authenticated/compare'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'
import { Route as AuthenticatedSimulationNewRouteImport } from './routes/_authenticated/simulation.new'
import { Route as AuthenticatedSimulationIdRouteImport } from './routes/_authenticated/simulation.$id'
import { Route as AuthenticatedSimulationIdAnalyticsRouteImport } from './routes/_authenticated/simulation.$id.analytics'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOptimizeRoute = AuthenticatedOptimizeRouteImport.update({
  id: '/optimize',
  path: '/optimize',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFuelsRoute = AuthenticatedFuelsRouteImport.update({
  id: '/fuels',
  path: '/fuels',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEnginesRoute = AuthenticatedEnginesRouteImport.update({
  id: '/engines',
  path: '/engines',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDatasetsRoute = AuthenticatedDatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompareRoute = AuthenticatedCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSimulationNewRoute =
  AuthenticatedSimulationNewRouteImport.update({
    id: '/simulation/new',
    path: '/simulation/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSimulationIdRoute =
  AuthenticatedSimulationIdRouteImport.update({
    id: '/simulation/$id',
    path: '/simulation/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSimulationIdAnalyticsRoute =
  AuthenticatedSimulationIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedSimulationIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/compare': typeof AuthenticatedCompareRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/datasets': typeof AuthenticatedDatasetsRoute
  '/engines': typeof AuthenticatedEnginesRoute
  '/fuels': typeof AuthenticatedFuelsRoute
  '/optimize': typeof AuthenticatedOptimizeRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/simulation/$id': typeof AuthenticatedSimulationIdRouteWithChildren
  '/simulation/new': typeof AuthenticatedSimulationNewRoute
  '/simulation/$id/analytics': typeof AuthenticatedSimulationIdAnalyticsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/compare': typeof AuthenticatedCompareRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/datasets': typeof AuthenticatedDatasetsRoute
  '/engines': typeof AuthenticatedEnginesRoute
  '/fuels': typeof AuthenticatedFuelsRoute
  '/optimize': typeof AuthenticatedOptimizeRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/simulation/$id': typeof AuthenticatedSimulationIdRouteWithChildren
  '/simulation/new': typeof AuthenticatedSimulationNewRoute
  '/simulation/$id/analytics': typeof AuthenticatedSimulationIdAnalyticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/assistant': typeof AuthenticatedAssistantRoute
  '/_authenticated/compare': typeof AuthenticatedCompareRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/datasets': typeof AuthenticatedDatasetsRoute
  '/_authenticated/engines': typeof AuthenticatedEnginesRoute
  '/_authenticated/fuels': typeof AuthenticatedFuelsRoute
  '/_authenticated/optimize': typeof AuthenticatedOptimizeRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/simulation/$id': typeof AuthenticatedSimulationIdRouteWithChildren
  '/_authenticated/simulation/new': typeof AuthenticatedSimulationNewRoute
  '/_authenticated/simulation/$id/analytics': typeof AuthenticatedSimulationIdAnalyticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/assistant'
    | '/compare'
    | '/dashboard'
    | '/datasets'
    | '/engines'
    | '/fuels'
    | '/optimize'
    | '/reports'
    | '/settings'
    | '/api/chat'
    | '/simulation/$id'
    | '/simulation/new'
    | '/simulation/$id/analytics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/assistant'
    | '/compare'
    | '/dashboard'
    | '/datasets'
    | '/engines'
    | '/fuels'
    | '/optimize'
    | '/reports'
    | '/settings'
    | '/api/chat'
    | '/simulation/$id'
    | '/simulation/new'
    | '/simulation/$id/analytics'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/assistant'
    | '/_authenticated/compare'
    | '/_authenticated/dashboard'
    | '/_authenticated/datasets'
    | '/_authenticated/engines'
    | '/_authenticated/fuels'
    | '/_authenticated/optimize'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/api/chat'
    | '/_authenticated/simulation/$id'
    | '/_authenticated/simulation/new'
    | '/_authenticated/simulation/$id/analytics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/optimize': {
      id: '/_authenticated/optimize'
      path: '/optimize'
      fullPath: '/optimize'
      preLoaderRoute: typeof AuthenticatedOptimizeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fuels': {
      id: '/_authenticated/fuels'
      path: '/fuels'
      fullPath: '/fuels'
      preLoaderRoute: typeof AuthenticatedFuelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/engines': {
      id: '/_authenticated/engines'
      path: '/engines'
      fullPath: '/engines'
      preLoaderRoute: typeof AuthenticatedEnginesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/datasets': {
      id: '/_authenticated/datasets'
      path: '/datasets'
      fullPath: '/datasets'
      preLoaderRoute: typeof AuthenticatedDatasetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compare': {
      id: '/_authenticated/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof AuthenticatedCompareRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/simulation/new': {
      id: '/_authenticated/simulation/new'
      path: '/simulation/new'
      fullPath: '/simulation/new'
      preLoaderRoute: typeof AuthenticatedSimulationNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/simulation/$id': {
      id: '/_authenticated/simulation/$id'
      path: '/simulation/$id'
      fullPath: '/simulation/$id'
      preLoaderRoute: typeof AuthenticatedSimulationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/simulation/$id/analytics': {
      id: '/_authenticated/simulation/$id/analytics'
      path: '/analytics'
      fullPath: '/simulation/$id/analytics'
      preLoaderRoute: typeof AuthenticatedSimulationIdAnalyticsRouteImport
      parentRoute: typeof AuthenticatedSimulationIdRoute
    }
  }
}

interface AuthenticatedSimulationIdRouteChildren {
  AuthenticatedSimulationIdAnalyticsRoute: typeof AuthenticatedSimulationIdAnalyticsRoute
}

const AuthenticatedSimulationIdRouteChildren: AuthenticatedSimulationIdRouteChildren =
  {
    AuthenticatedSimulationIdAnalyticsRoute:
      AuthenticatedSimulationIdAnalyticsRoute,
  }

const AuthenticatedSimulationIdRouteWithChildren =
  AuthenticatedSimulationIdRoute._addFileChildren(
    AuthenticatedSimulationIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRoute
  AuthenticatedCompareRoute: typeof AuthenticatedCompareRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDatasetsRoute: typeof AuthenticatedDatasetsRoute
  AuthenticatedEnginesRoute: typeof AuthenticatedEnginesRoute
  AuthenticatedFuelsRoute: typeof AuthenticatedFuelsRoute
  AuthenticatedOptimizeRoute: typeof AuthenticatedOptimizeRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSimulationIdRoute: typeof AuthenticatedSimulationIdRouteWithChildren
  AuthenticatedSimulationNewRoute: typeof AuthenticatedSimulationNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssistantRoute: AuthenticatedAssistantRoute,
  AuthenticatedCompareRoute: AuthenticatedCompareRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDatasetsRoute: AuthenticatedDatasetsRoute,
  AuthenticatedEnginesRoute: AuthenticatedEnginesRoute,
  AuthenticatedFuelsRoute: AuthenticatedFuelsRoute,
  AuthenticatedOptimizeRoute: AuthenticatedOptimizeRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSimulationIdRoute: AuthenticatedSimulationIdRouteWithChildren,
  AuthenticatedSimulationNewRoute: AuthenticatedSimulationNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
